export PROD_ADMIN_EMAIL='devops@chegg.com'
export PROD_ADMIN_PASSWORD='rI9oNg9Ack1noI'
export TEST_ADMIN_EMAIL='devops@chegg.com'
export TEST_ADMIN_PASSWORD='@p!Ha$hR0ck3t'
export DEFAULT_USER=`whoami`
export PIP_REQUIRE_VIRTUALENV=true
export WORKON_HOME=~/.virtualenvs
source /Users/satyajit.roy/.rvm/scripts/rvm
source /usr/local/bin/virtualenvwrapper.sh
